name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: doc build
        run: |
          scripts/hhb_doc_docker.sh
#          mkdir docs/_build
#          mkdir docs/_build/html
#          echo "Hello hhb" > docs/_build/html/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/doc' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
